# Generated by Django 4.2.2 on 2023-06-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Worksite",
            fields=[
                ("worksite_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sector",
                    models.CharField(
                        choices=[("GO", "Gros Oeuvre"), ("TCE", "Tout Corps D'état")],
                        default="GO",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("adress", models.CharField(max_length=200)),
                ("started", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("etudes", "Etudes"),
                            ("gros_oeuvre", "Gros Oeuvre"),
                            ("tous_corps_detat", "Tous Corps D'Etat"),
                            ("finitions", "Finitions"),
                            ("termine", "Terminé"),
                        ],
                        default="etudes",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.client"
                    ),
                ),
            ],
            options={
                "ordering": ["-started"],
            },
        ),
    ]
