# Generated by Django 4.2.2 on 2023-08-02 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worksiteemployee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="worksiteemployee",
            name="worksite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.worksite"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="staff",
                to="api.employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="worksiteemployee",
            constraint=models.UniqueConstraint(
                fields=("worksite", "user"), name="unique_management"
            ),
        ),
    ]
