# Generated by Django 4.2.2 on 2023-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksite",
            name="sector",
            field=models.CharField(
                choices=[("GO", "Gros Oeuvre"), ("TCE", "Tout Corps D'état")],
                default="GO",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Sector",
        ),
    ]
