# Generated by Django 4.2.2 on 2023-08-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_worksite_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("notif_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.employee"
                    ),
                ),
            ],
        ),
    ]
