# Generated by Django 4.2.2 on 2023-06-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_worksite_sector_delete_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksite",
            name="started",
            field=models.DateField(),
        ),
    ]
