# Generated by Django 4.2.2 on 2023-06-26 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_sitedirector_sitesupervisor_siteforeman_management"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="management",
            name="user",
        ),
        migrations.AddField(
            model_name="management",
            name="staff_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="staff_type",
            field=models.CharField(
                choices=[
                    ("director", "Director"),
                    ("supervisor", "Supervisor"),
                    ("foreman", "Foreman"),
                ],
                default="foreman",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitedirector",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sitesupervisor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
