# Generated by Django 4.2.2 on 2023-08-28 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_worksitestock_warehousestock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("line_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Retour",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 8, 29, 7, 41, 16, 799980, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("threshold", models.IntegerField(default=0)),
                ("validation1", models.BooleanField(default=False)),
                ("validation2", models.BooleanField(default=False)),
                ("validation3", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("edition", "édition"),
                            ("validation", "en validation"),
                            ("confirmed", "confirmé"),
                            ("refused", "refusée"),
                        ],
                        default="edition",
                        max_length=50,
                    ),
                ),
                ("retour_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "worksite",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.worksite",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RetourLine",
            fields=[
                ("line_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "retour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.retour"
                    ),
                ),
            ],
            options={
                "unique_together": {("retour", "product")},
            },
        ),
        migrations.DeleteModel(
            name="Return",
        ),
        migrations.AddField(
            model_name="order",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 29, 7, 41, 16, 799980, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("edition", "édition"),
                    ("validation", "en validation"),
                    ("confirmed", "confirmé"),
                    ("refused", "refusée"),
                ],
                default="edition",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="threshold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="validation1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="validation2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="validation3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="worksite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.worksite",
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="threshold",
            field=models.IntegerField(
                choices=[(0, ""), (1, "courant"), (2, "important"), (3, "critique")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.order"
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderline",
            unique_together={("order", "product")},
        ),
    ]
