# Generated by Django 4.2.2 on 2023-08-31 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_employee_threshold_alter_order_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="validation1",
        ),
        migrations.RemoveField(
            model_name="order",
            name="validation2",
        ),
        migrations.RemoveField(
            model_name="order",
            name="validation3",
        ),
        migrations.RemoveField(
            model_name="retour",
            name="validation1",
        ),
        migrations.RemoveField(
            model_name="retour",
            name="validation2",
        ),
        migrations.RemoveField(
            model_name="retour",
            name="validation3",
        ),
        migrations.AddField(
            model_name="order",
            name="validation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="retour",
            name="validation",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 1, 10, 40, 50, 499063, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retour",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 1, 10, 40, 50, 499063, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
