# Generated by Django 4.2.2 on 2023-09-01 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_order_date_time_alter_retour_date_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("expected_date_time", models.DateTimeField()),
                ("real_date_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "planifiée"),
                            ("delayed", "retard"),
                            ("loading", "chargement"),
                            ("ongoing", "en routes"),
                            ("unloading", "déchargement"),
                            ("completed", "terminée"),
                            ("uncompleted", "incomplète"),
                            ("canceled", "annulée"),
                            ("failure", "échec"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="date_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 7, 50, 6, 279580, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name="retour",
            name="date_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 7, 50, 6, 279580, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name="DeliveryLine",
            fields=[
                ("delivery_line_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "delivery",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.delivery"),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.product"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="api.order"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="retour",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="api.retour"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="worksite",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.worksite"),
        ),
    ]
