# Generated by Django 4.2.2 on 2023-09-01 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_delivery_alter_order_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="real_date_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 2, 7, 59, 14, 168571, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retour",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 2, 7, 59, 14, 168571, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
