# Generated by Django 4.2.2 on 2023-09-01 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_delivery_order_alter_delivery_retour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 2, 8, 15, 30, 704383, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retour",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 2, 8, 15, 30, 704383, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
