# Generated by Django 4.2.2 on 2023-09-07 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_alter_order_date_time_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 8, 10, 18, 55, 473551, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retour",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 8, 10, 18, 55, 473551, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
