# Generated by Django 4.2.2 on 2023-08-03 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_confirmed",
        ),
    ]
